# -*- mode:python -*-

# Copyright (c) 2006 The Regents of The University of Michigan
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import sys

Import('*')

if 'POWER8CPU' in env['CPU_MODELS']:
    SimObject('O3Execution/POWER8FUPool.py')
    SimObject('O3Execution/POWER8FuncUnitConfig.py')
    SimObject('POWER8CPU.py')

    
    Source('cpu.cc')
    
    Source('dyn_inst.cc')
    Source('IFU/fetch.cc')
    Source('IFU/early_decode.cc')
    Source('IFU/decode.cc')
    Source('ISU/free_list.cc')
    Source('O3Execution/fu_pool.cc')
    Source('O3Execution/iew.cc')
    Source('O3Execution/inst_queue.cc')
    Source('O3Execution/lsq.cc')
    Source('O3Execution/lsq_unit.cc')
    Source('O3Execution/mem_dep_unit.cc')
    Source('regfile.cc')
    Source('ISU/rename.cc')
    Source('ISU/rename_map.cc')
    Source('O3Execution/scoreboard.cc')
    Source('O3Execution/store_set.cc')
    Source('ISU/commit.cc')
    Source('ISU/rob.cc')
    Source('thread_context.cc')
    Source('thread_state.cc')

    DebugFlag('POWER8CommitRate')
    DebugFlag('POWER8IEW')
    DebugFlag('POWER8IQ')
    DebugFlag('POWER8LSQ')
    DebugFlag('POWER8LSQUnit')
    DebugFlag('POWER8MemDepUnit')
    DebugFlag('POWER8CPU')
    DebugFlag('POWER8ROB')
    DebugFlag('POWER8Rename')
    DebugFlag('POWER8Scoreboard')
    DebugFlag('POWER8StoreSet')
    DebugFlag('POWER8Writeback')

    CompoundFlag('POWER8CPUAll', [ 'Fetch', 'Decode', 'Rename', 'IEW', 'Commit',
        'IQ', 'ROB', 'FreeList', 'LSQ', 'LSQUnit', 'StoreSet', 'MemDepUnit',
        'DynInst', 'O3CPU', 'Activity', 'Scoreboard', 'Writeback' ])

    SimObject('POWER8Checker.py')
    Source('checker.cc')
